V0.2.0 jack nelson
Semi-ATE/STDF pull request #53
Opened 2022-10-19 07:03 UTC by JackNelson

## Description of Changes

See #52 

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: JackNelson

2022-10-19 07:07 UTC, JackNelson commented
pytest is still failing, I suspect it is due to not reserving the bits on the `set_value` and `_pack_item` side.  I am not as familiar with those as I have used this package only to read in files.  I can also confirm #52 as a valid issue since I ran into this for reading in files from 2 separate semiconductor suppliers that follow the V4 standard.

2022-10-19 07:09 UTC, nerohmot requested changes
The `__version__` string should remain "0.0.0".
If one installs from master (aka: use a none-released version), one should see this as the version is `0.0.0`.
A release of the package will overwrite this with the correct (release) version.

2022-10-19 16:01 UTC, JackNelson commented
version was reverted back.  On the next release I would suggest upping the minor version (0.2.0) as this change seems significant in interpretting files.

Please advise on changes required, if any in the `set_value()` and `_pack_item()` methods.  I'm unsure what is required there to remedy the failing pytests. 

- `set_value()`
  - https://github.com/Semi-ATE/STDF/blob/main/Semi_ATE/STDF/STDR.py#L630-L633
  - https://github.com/Semi-ATE/STDF/blob/main/Semi_ATE/STDF/STDR.py#L674-L678

- `_pack_item()
  - https://github.com/Semi-ATE/STDF/blob/main/Semi_ATE/STDF/STDR.py#L1200-L1210

2022-10-20 05:55 UTC, nerohmot approved these changes

2022-10-20 05:55 UTC, merged